model_list:
  # The AWS ID or ARN of an inference profile that contains this model   
  - model_name: bedrock-claude-4.8-opus
    litellm_params:
      model: us.anthropic.claude-opus-4-8
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_session_token: os.environ/AWS_SESSION_TOKEN
      aws_region_name: us-east-1
  - model_name: bedrock-claude-4.6-sonnet
    litellm_params:
      model: us.anthropic.claude-sonnet-4-6
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_session_token: os.environ/AWS_SESSION_TOKEN
      aws_region_name: us-east-1        
  - model_name: bedrock-claude-4.5-haiku
    litellm_params:
      model: us.anthropic.claude-haiku-4-5-20251001-v1:0
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
      aws_session_token: os.environ/AWS_SESSION_TOKEN
      aws_region_name: us-east-1  

  - model_name: claude-sonnet-4.6
    litellm_params:
      model: claude-sonnet-4-6
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-haiku-4.5
    litellm_params:
      model: claude-haiku-4-5-20251001
      api_key: os.environ/ANTHROPIC_API_KEY  

  # GitHub Copilot Available Models (2026.06.26)
  # Using VSCode version: 1.126.0
  # by running `npx copilot-api@latest start` in terminal
  # Available models:
  # claude-opus-4.6
  # claude-sonnet-4.6
  # gemini-3.5-flash
  # gpt-5.3-codex
  # gpt-5.4-mini
  # gpt-5.4
  # trajectory-compaction
  # gpt-5-mini
  # gpt-4o-mini-2024-07-18
  # gpt-4o-2024-11-20
  # gpt-4o-2024-08-06
  # text-embedding-3-small
  # text-embedding-3-small-inference
  # claude-sonnet-4.5
  # claude-opus-4.5
  # claude-haiku-4.5
  # gemini-2.5-pro
  # gpt-4.1-2025-04-14
  # gpt-41-copilot
  # gpt-3.5-turbo-0613
  # gpt-4
  # gpt-4-0613
  # gpt-4-0125-preview
  # gpt-4o-2024-05-13
  # gpt-4-o-preview
  # gpt-4.1
  # gpt-3.5-turbo
  # gpt-4o-mini
  # gpt-4o
  # text-embedding-ada-002
  - model_name: github-copilot-claude-opus-4.6
    litellm_params:
      model: github_copilot/claude-opus-4.6
      extra_headers:
        {
          "editor-version": "vscode/1.85.1",
          "editor-plugin-version": "copilot/1.155.0",
          "Copilot-Integration-Id": "vscode-chat",
          "user-agent": "GithubCopilot/1.155.0"
        }  
  - model_name: github-copilot-claude-sonnet-4.6
    litellm_params:
      model: github_copilot/claude-sonnet-4.6
      extra_headers:
        {
          "editor-version": "vscode/1.85.1",
          "editor-plugin-version": "copilot/1.155.0",
          "Copilot-Integration-Id": "vscode-chat",
          "user-agent": "GithubCopilot/1.155.0"
        }
  - model_name: github-copilot-gpt-5.3-codex
    litellm_params:
      model: github_copilot/gpt-5.3-codex
      extra_headers:
        {
          "editor-version": "vscode/1.104.1",
          "editor-plugin-version": "copilot/1.155.0",
          "Copilot-Integration-Id": "vscode-chat",
          "user-agent": "GithubCopilot/1.155.0"
        }          
  - model_name: github-copilot-gpt-5.4 
    litellm_params:
      model: github_copilot/gpt-5.4
      extra_headers:
        {
          "editor-version": "vscode/1.85.1",
          "editor-plugin-version": "copilot/1.155.0",
          "Copilot-Integration-Id": "vscode-chat",
          "user-agent": "GithubCopilot/1.155.0"
        }          
  - model_name: github-copilot-gemini-2.5-pro
    litellm_params:
      model: github_copilot/gemini-2.5-pro
      extra_headers:
        {
          "editor-version": "vscode/1.85.1",
          "editor-plugin-version": "copilot/1.155.0",
          "Copilot-Integration-Id": "vscode-chat",
          "user-agent": "GithubCopilot/1.155.0"
        }

  - model_name: github-gpt-4o-mini
    litellm_params:
      model: github/gpt-4o-mini
      # GitHub Personal Access Token
      api_key: os.environ/GITHUB_API_KEY

  - model_name: gemini-2.5-pro
    litellm_params:
      model: gemini/gemini-2.5-pro
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY  

  - model_name: openrouter-google-gemma-4-31b-it
    litellm_params:
      model: openrouter/google/gemma-4-31b-it:free
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: openrouter-google-gemma-4-26b-a4b-it
    litellm_params:
      model: openrouter/google/gemma-4-26b-a4b-it:free
      api_key: os.environ/OPENROUTER_API_KEY      
  - model_name: openrouter-qwen3-next-80b-a3b-instruct
    litellm_params:
      model: openrouter/qwen/qwen3-next-80b-a3b-instruct:free
      api_key: os.environ/OPENROUTER_API_KEY
  - model_name: openrouter-qwen3-coder
    litellm_params:
      model: openrouter/qwen/qwen3-coder:free
      api_key: os.environ/OPENROUTER_API_KEY      

  - model_name: groq-qwen3-32b
    litellm_params:
      model: groq/qwen/qwen3-32b
      api_key: os.environ/GROQ_API_KEY
  - model_name: groq-qwen3.6-27b
    litellm_params:
      model: groq/qwen/qwen3.6-27b
      api_key: os.environ/GROQ_API_KEY
  - model_name: groq-llama-4-scout-17b-16e-instruct
    litellm_params:
      model: groq/meta-llama/llama-4-scout-17b-16e-instruct
      api_key: os.environ/GROQ_API_KEY
  - model_name: groq-llama-3.3-70b-versatile
    litellm_params:
      model: groq/llama-3.3-70b-versatile
      api_key: os.environ/GROQ_API_KEY